name = "clash-sub-converter"
main = "src/index.js"
compatibility_date = "2025-06-05"

# R2 存储桶绑定 - 用于存放生成的订阅文件
[[r2_buckets]]
binding = "R2_SUBS_BUCKET"
bucket_name = "my-clash-subs"

# R2 存储桶绑定 - 用于存放前端静态文件
[[r2_buckets]]
binding = "R2_STATIC_ASSETS"
bucket_name = "clash-converter-static"

# KV 命名空间绑定 - 用于缓存远程订阅内容
# [[kv_namespaces]]
# binding = "KV_REMOTE_CACHE"
# id = "b46100b9a05a4f43a5396959a122d648"  # 替换为你的KV命名空间ID
# preview_id = "remote_sub_cache_preview"  # 可选，用于开发预览

# 自动上传静态页面至存储桶
[triggers]
deploy = ["wrangler r2 bucket put clash-converter-static ./public --recursive"]
deploy = ["wrangler r2 bucket put my-clash-subs ./public --recursive"]
