name = "sub-store"  # 使用CI期望的名称
compatibility_date = "2025-06-04"
main = "src/index.js"
workers_dev = true
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
# 添加KV命名空间用于存储HTML
kv_namespaces = [
  { binding = "ASSETS", id = "b46100b9a05a4f43a5396959a122d648" } # 替换为实际ID
]

[site]
bucket = "./public"
entry-point = "src"
