export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    
    try {
      // 返回前端页面
      if (url.pathname === '/' || url.pathname === '/index.html') {
        const html = await env.ASSETS.fetch(
          new Request(`${url.origin}/index.html`)
        );
        return new Response(await html.text(), {
          headers: { 
            'Content-Type': 'text/html; charset=utf-8',
            'Cache-Control': 'max-age=3600'
          }
        });
      }
      
      // 处理转换请求
      if (url.pathname === '/convert') {
        if (request.method === 'POST') {
          const { url: subUrl } = await request.json();
          
          // 简单的转换逻辑（实际应用中需要更完整的实现）
          const now = new Date();
          const config = `# Clash config generated by converter
# Original URL: ${subUrl}
# Generated at: ${now.toISOString()}

mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: "Demo Node"
    type: ss
    server: proxy.example.com
    port: 443
    cipher: aes-256-gcm
    password: "your-password"
    udp: true

proxy-groups:
  - name: "Auto Select"
    type: url-test
    proxies: ["Demo Node"]
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rules:
  - DOMAIN-SUFFIX,google.com,Auto Select
  - DOMAIN-SUFFIX,youtube.com,Auto Select
  - GEOIP,CN,DIRECT
  - MATCH,Auto Select`;
          
          return new Response(JSON.stringify({ success: true, config }), {
            headers: { 
              'Content-Type': 'application/json',
              'Access-Control-Allow-Origin': '*'
            }
          });
        }
        return new Response('Method not allowed', { status: 405 });
      }
      
      return new Response('Not found', { status: 404 });
      
    } catch (error) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Internal server error',
        message: error.message
      }), {
        status: 500,
        headers: { 
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      });
    }
  }
}
